title: QAction Documentation
description: Getting Started
theme: just-the-docs

url: https://qflowsystems.github.io/docs.qflow.com

color_scheme: custom
logo: "/assets/svg/logo.svg"
favicon_ico: "/assets/svg/favicon.svg"

callouts:
  note:
    title: " Note"
    color: green
  highlight:
    color: yellow
  important:
    title: " Important"
    color: orange
  new:
    title: " New"
    color: primary
  warning:
    title: " Warning"
    color: red

search_enabled: true
heading_anchors: true
nav_enabled: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "Back to QFlow Home":
    - "//goqflow.com"
